version: '3.3'

services:
  mysqldb:
    container_name: mysql_data_bases
    env_file: ./src/common/envs/.env
    image: mysql
    restart: always
    command: 
      --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: meinsm
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
  
volumes:
  mysql:
  mysql_config:
